### ISSUE TITLE
Upgrading ReBind causes crash on startup

### ISSUE THREAD

**Issue by evhub** [AustereTony-MCMods/ReBind#1]
Just upgraded ReBind from 1.0 to 2.2.0 and the game crashed immediately upon starting up, without ever reaching the forge loading screen or producing a crash report.

**Comment by AustereTony-MCMods** [comment]
Hi! I need more info. Please give me game version and full mod version. Are the versions exactly the same? If no, i'm assuming this is happening because of wrong core transformations.
