### ISSUE TITLE
ReBind causes crash on startup

### ISSUE THREAD

**Issue by sashazell** [AustereTony-MCMods/ReBind#2]
[debug.log](https://github.com/AustereTony-MCMods/ReBind/files/2072520/debug.log)
[latest.log](https://github.com/AustereTony-MCMods/ReBind/files/2072521/latest.log)
[2018-06-05-5.log.gz](https://github.com/AustereTony-MCMods/ReBind/files/2072522/2018-06-05-5.log.gz)
[debug-1.log.gz](https://github.com/AustereTony-MCMods/ReBind/files/2072523/debug-1.log

Version: game - 1.12.2-forge1.12.2-14.23.4.2707  mod- rebind-1.12.2-2.4.0

**Comment by AustereTony-MCMods** [comment]
Hello. I am grateful for the detailed log. The game crash was caused by ReBind incompatibility with Optifine (for MC 1.9.4+). I just found out today and fixed it in update 2.4.1, so please check it when it be available on Curse.
