### ISSUE TITLE
how to make original key of mods disabled

### ISSUE THREAD

**Issue by ghost** [AustereTony-MCMods/ReBind#4]
The default key of minemenu mod is "R",i rebind it to ctrol+r,when  enter game,both "r" and "ctrol +r" work,how can  i  make "r"　invalid？
here is my json file
`"minemenu_open_menu": { "holder": "", "name": "", "category": "mc.misc", "key": 19, "mod": "CONTROL", "enabled": true}`

**Comment by AustereTony-MCMods** [comment]
First, sorry for late answer. 
This problem is related to MineMenu, so you should ask MM author. Anyway i fixed this in ver: 2.7.4 for 1.12.2. Combinations now will work properly. Consider it solved.
